### PR TITLE
Adding single and notrunc tag options

### LINKED ISSUE #49: []string as non-positional argument
When using `[]string` as the type for a non-positional argument, for example:

```go
type MyArgs struct {
    Commands []string `arg:"-c,help:commands to execute"`
}
```

The syntax that is usable, is the following: `-c "command1" "command2"`, however one would expect this to behave similar to how other standard command line apps do it: `-c "command1" -c "command2"`.

Here is some example output from `usql` which is using `go-arg` and for which I'd like to accomplish the same style syntax as `psql` (which is also the same as bash and other standard cli programs):

```sh
ken@ken-desktop:~/src/go/src/github.com/knq/usql$ ./usql pg://booktest:booktest@localhost/ -c 'select * from books;' -c 'select * from authors'
2017/03/03 12:41:52 >>> commands: [select * from authors]
  author_id |      name       
+-----------+----------------+
          1 | Unknown Master  
(1 rows)

ken@ken-desktop:~/src/go/src/github.com/knq/usql$ ./usql pg://booktest:booktest@localhost/ -c='select * from books;' -c='select * from authors'
2017/03/03 12:42:00 >>> commands: [select * from authors]
  author_id |      name       
+-----------+----------------+
          1 | Unknown Master  
(1 rows)

ken@ken-desktop:~/src/go/src/github.com/knq/usql$ ./usql pg://booktest:booktest@localhost/ -c 'select * from books;' 'select * from authors'
2017/03/03 12:42:11 >>> commands: [select * from books; select * from authors]
  book_id | author_id | isbn | booktype |        title         | year |            available             |      tags        
+---------+-----------+------+----------+----------------------+------+----------------------------------+-----------------+
        1 |         1 |    1 | FICTION  | my book title        | 2016 | 2017-03-03T00:21:37.613263+07:00 | {}               
        2 |         1 |    2 | FICTION  | changed second title | 2016 | 2017-03-03T00:21:37.613263+07:00 | {cool,disastor}  
        3 |         1 |    3 | FICTION  | the third book       | 2001 | 2017-03-03T00:21:37.613263+07:00 | {cool}           
(3 rows)

  author_id |      name       
+-----------+----------------+
          1 | Unknown Master  
(1 rows)
```

As you can see above, the parsing for `[]string` seems to be the same as a positional argument only. Ideally, one should be able to mix and match the named parameters, and positional arguments:

```sh
$ usql -c 'command1' pg://database -c 'command2'

# the above should work the same as the following:
$ usql -c 'command1' -c 'command2' pg://database
```

I'm happy to do the work for this, but would like approval first to know if I write the PR, it would be accepted. Thanks in advance!

### PR DESCRIPTION
**Pull request by kenshaw**
As outlined in #49, there is a need to mimic the behavior of other
applications by interweaving positional and non-positional parameters.

This change adds the 'single' option that will force a arg of type
[]string to only read only the next supplied value

For example, when dealing with the following arg type:

type MyArgs struct {
    Pos []string `arg:"positional"`
    Single []string `arg:"-s,single"`
}

This commit will parse the following command line:

./app pos1 pos2 -s=single1 -s=single2 pos3 -s=single3 pos4

Such that MyArgs.Pos will be [pos1 pos2 pos3 pos4] and Single will be
[single1 single2 single3].

Additionally, because this change needed to modify the way the
'multiple' (ie, how values in slices are accumulated via setSlice) spec
type works, it was thought to be prudent to add a 'notrunc' option that
allows for default values to be assigned to positional args, so that
they can continue to be accumulated, instead of truncating the default
slice values.

Unit tests for the above have also been written and are included in this
commit, as well as the addition of a section to README.md and a func
defined in example_test.go.

Fixes #49

### CODE REVIEW

**Comment by kenshaw** [comment]
Let me know if this is good, or if more work is necessary. I did not originally plan to also add the `notrunc` option, but thought it best/prudent to provide it, should a positional arg need a default value. Thanks in advance!

**Comment by alexflint** [comment]
I like the implementation of the "single" tag, although I think it should be named something else because the argument itself is still in some sense a "multiple" argument. Perhaps "repeat"? I'm open to suggestions :)

As for the "notrunc" tag, is the only purpose of this to allow arguments that append to their default values, rather than overwriting? If so then I would rather avoid adding that and instead let users manually append the default value.

Finally, can you add a test that uses the "single" flag in conjunction with a default value?

Other than that I'm happy to merge this!

**Comment by kenshaw** [comment]
I can't think of a different name than repeat/single at the moment. You're right about 'single', it's not a good name.

You want the notrunc option removed then?

And yes, I can add a 'single' test with a default value. I'll do that in the morning.

**Comment by kenshaw** [comment]
For the name, how about 'readone' or something? I don't have any clues here. I agree that `single` clashes with the code's concept of `multiple`. However, `repeat` to me seems to be the opposite behavior. What about `norepeat`?

**Comment by alexflint** [comment]
Yeah can you remove the "notrunc" option? For the name of the tag, how about "separate"?

**Comment by kenshaw** [comment]
Yes -- will do so shortly. Thanks!

**Comment by kenshaw** [comment]
Made the changes as requested. Let me know if this works. Thanks!

**Comment by kenshaw** [comment]
Let me know if there's anything else that I need to change. I'm glad to do so. I'm in the process of doing the first "release" of github.com/knq/usql and would like to properly vendor dependencies moving forward. Appreciate it, thanks!

**Comment by alexflint** [comment]
Thanks for the change @kenshaw

**Comment by kenshaw** [comment]
Awesome, thanks!

**Pull request merged**
