### PR TITLE
add FailSubcommand, WriteUsageForSubcommand, WriteHelpForSubcommand

### LINKED ISSUE #134: Find a way to print help message for nested subcommands
I have an app like this:
app
    pack
        build
        extract
        generate
If I run "app pack", nothing happens. I have to run "app pack --help" to get something useful, which is probably not emediately obvious.

### PR DESCRIPTION
**Pull request by alexflint**
Closes #134 #135 #139 

This pr makes it possible to print usage and help text for explicit subcommands. It adds three new functions:
```
Parser.WriteUsageForSubcommand
Parser.WriteHelpForSubcommand
Parser.FailSubcommand
```

These behave like their non-subcommand cousins, except that they also take a subcommand name (or a sequence of subcommand names in the case of nested subcommands)

### CODE REVIEW

**Comment by Keithcat1** [comment]
Thanks for this. Is there a way to enable printing help messages by default for nested subcommands? As I understand it, even with this pull request merged I would still have to call Parser.WriteHelpForSubcommand in each problematic subcommands code.

**Comment by Keithcat1** [comment]
Why isn't this merged yet? It doesn't seem to blocking on anything.

**Comment by chrisgoffinet** [comment]
@alexflint could we merge this?

**Comment by xvello** [comment]
Hello @alexflint, thanks a lot for your work on this!

It does look like #139 is not completely fixed yet though: we are still [printing `p.description`](https://github.com/alexflint/go-arg/blob/bf32f082479c88da7bcf4c4765a70e3a357d9dfc/usage.go#L221-L223), which is obtained by calling `Description()` on the root command, not the subcommand selected by the user.

To make it work, we need that description to be added to the `command` struct, either as a pointer to the `Described` interface, or as a string. From a quick investigation, this does not seem trivial to implement, as `cmdFromStruct` takes a `reflect.Type` and not the struct itself. 

Do you have any opinion on how that could be implemented?

**Comment by alexflint** [comment]
@xvello you are exactly right. I've reopened #139.

**Pull request merged**
